ALTER TABLE `{$prefix}users`
    CHANGE `username` `username` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    CHANGE `password` `password` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    CHANGE `reset_password` `reset_password` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    CHANGE `email` `email` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    CHANGE `group_id` `group_id` BIGINT(20) UNSIGNED NOT NULL,
    CHANGE `banned` `banned` TINYINT(1) NOT NULL DEFAULT '0',
    CHANGE `timestamp` `timestamp` DATETIME NULL DEFAULT NULL,
    CHANGE `ip` `ip` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    CHANGE `real_name` `real_name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    CHANGE `gender` `gender` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
    CHANGE `about` `about` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    CHANGE `enable_sounds` `enable_sounds` TINYINT(1) NOT NULL DEFAULT '1',
    CHANGE `use_default_timestamp_settings` `use_default_timestamp_settings` TINYINT(1) NOT NULL DEFAULT '1',
    CHANGE `enable_timestamps` `enable_timestamps` TINYINT(1) NOT NULL DEFAULT '1',
    CHANGE `ts_24_hour` `ts_24_hour` TINYINT(1) NOT NULL DEFAULT '0',
    CHANGE `ts_show_seconds` `ts_show_seconds` TINYINT(1) NOT NULL DEFAULT '0',
    CHANGE `ts_show_ampm` `ts_show_ampm` TINYINT(1) NOT NULL DEFAULT '0',
    CHANGE `ts_show_date` `ts_show_date` TINYINT(1) NOT NULL DEFAULT '0',
    CHANGE `enable_styles` `enable_styles` TINYINT(1) NOT NULL DEFAULT '1',
    CHANGE `message_font_size` `message_font_size` TINYINT(3) UNSIGNED NOT NULL DEFAULT '12',
    CHANGE `message_font_color` `message_font_color` CHAR(6) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '000000',
    CHANGE `message_font_face` `message_font_face` BIGINT(20) UNSIGNED NOT NULL DEFAULT '1',
    CHANGE `group_id` `group_id` BIGINT( 20 ) UNSIGNED NULL DEFAULT NULL;